---
name: "Twingate Connector"
version: "1.0.0"
slug: "twingate-connector"
description: "Twingate connector for secure network access"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
init: false
host_network: true
map:
  - config:rw
options:
  network: ""
  access_token: ""
  refresh_token: ""
  container_name: "connector-name"
  network_mode: "host"
  log_level: "detailed"
  log_analytics: "v2"
schema:
  network: str
  access_token: str
  refresh_token: str
  container_name: str
  network_mode: list(host|bridge|none)
  log_level: list(minimal|basic|normal|detailed|debug)
  log_analytics: str
